// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"

	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/domain/entity"
)

type CreateTodoInput struct {
	TodoListID  string           `json:"todoListID"`
	Title       string           `json:"title"`
	Description *string          `json:"description,omitempty"`
	Priority    *entity.Priority `json:"priority,omitempty"`
	DueDate     *string          `json:"dueDate,omitempty"`
	AssigneeID  *string          `json:"assigneeID,omitempty"`
}

type CreateTodoListInput struct {
	DisplayName string `json:"displayName"`
}

type DeleteTodoInput struct {
	TodoListID string `json:"todoListID"`
	TodoID     string `json:"todoID"`
}

type DeleteTodoListInput struct {
	TodoListID string `json:"todoListID"`
}

type GetTodoInput struct {
	TodoListID string `json:"todoListID"`
	TodoID     string `json:"todoID"`
}

type GetTodoListInput struct {
	TodoListID string `json:"todoListID"`
}

type GetUserByEmailInput struct {
	Email string `json:"email"`
}

type GetUserByUsernameInput struct {
	Username string `json:"username"`
}

type GetUserInput struct {
	ID string `json:"id"`
}

type ListTodoListsInput struct {
	PageSize   *int    `json:"pageSize,omitempty"`
	Offset     *int    `json:"offset,omitempty"`
	NameSearch *string `json:"nameSearch,omitempty"`
}

type ListTodosInput struct {
	TodoListID  string             `json:"todoListID"`
	PageSize    *int               `json:"pageSize,omitempty"`
	Offset      *int               `json:"offset,omitempty"`
	Status      *entity.TodoStatus `json:"status,omitempty"`
	Priority    *entity.Priority   `json:"priority,omitempty"`
	TitleSearch *string            `json:"titleSearch,omitempty"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginOutput struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterOutput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Todo struct {
	ID          string            `json:"ID"`
	TodoListID  string            `json:"todoListID"`
	Title       string            `json:"title"`
	Description *string           `json:"description,omitempty"`
	Status      entity.TodoStatus `json:"status"`
	Priority    entity.Priority   `json:"priority"`
	DueDate     *time.Time        `json:"dueDate,omitempty"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
	AssigneeID  *string           `json:"assigneeID,omitempty"`
	Assignee    *User             `json:"assignee,omitempty"`
}

type TodoList struct {
	ID          string    `json:"ID"`
	DisplayName string    `json:"displayName"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type TodoListPage struct {
	TodoLists []*TodoList `json:"todoLists"`
	Total     int         `json:"total"`
}

type TodoPage struct {
	Todos []*Todo `json:"todos"`
	Total int     `json:"total"`
}

type UpdateTodoInput struct {
	TodoListID  string             `json:"todoListID"`
	TodoID      string             `json:"todoID"`
	Title       *string            `json:"title,omitempty"`
	Description *string            `json:"description,omitempty"`
	Status      *entity.TodoStatus `json:"status,omitempty"`
	Priority    *entity.Priority   `json:"priority,omitempty"`
	DueDate     *string            `json:"dueDate,omitempty"`
	AssigneeID  *string            `json:"assigneeID,omitempty"`
}

type UpdateTodoListInput struct {
	TodoListID  string  `json:"todoListID"`
	DisplayName *string `json:"displayName,omitempty"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
