// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/domain/entity"
)

type AuthPayload struct {
	Token string       `json:"token"`
	User  *entity.User `json:"user"`
}

type CreateTodoInput struct {
	Title       string           `json:"title"`
	Description *string          `json:"description,omitempty"`
	Priority    *entity.Priority `json:"priority,omitempty"`
	DueDate     *string          `json:"dueDate,omitempty"`
	AssigneeID  *string          `json:"assigneeID,omitempty"`
}

type CreateTodoListInput struct {
	DisplayName string `json:"displayName"`
}

type ListTodoListsInput struct {
	PageSize   *int    `json:"pageSize,omitempty"`
	Offset     *int    `json:"offset,omitempty"`
	NameSearch *string `json:"nameSearch,omitempty"`
}

type ListTodosInput struct {
	PageSize    *int               `json:"pageSize,omitempty"`
	Offset      *int               `json:"offset,omitempty"`
	Status      *entity.TodoStatus `json:"status,omitempty"`
	Priority    *entity.Priority   `json:"priority,omitempty"`
	TitleSearch *string            `json:"titleSearch,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type TodoListPage struct {
	TodoLists []*entity.TodoList `json:"todoLists"`
	Total     int                `json:"total"`
}

type TodoPage struct {
	Todos []*entity.Todo `json:"todos"`
	Total int            `json:"total"`
}

type UpdateTodoInput struct {
	Title       *string            `json:"title,omitempty"`
	Description *string            `json:"description,omitempty"`
	Status      *entity.TodoStatus `json:"status,omitempty"`
	Priority    *entity.Priority   `json:"priority,omitempty"`
	DueDate     *string            `json:"dueDate,omitempty"`
	AssigneeID  *string            `json:"assigneeID,omitempty"`
}

type UpdateTodoListInput struct {
	DisplayName *string `json:"displayName,omitempty"`
}
