package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strconv"

	"github.com/nghiapd-andpad/todo-project-intern/pkg/auth"
	"github.com/nghiapd-andpad/todo-project-intern/pkg/resourcename"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/domain/entity"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/domain/gateway"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/handler/dataloader"
	inputusecase "github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/usecase/todo/input"
)

// CreateTodoList is the resolver for the createTodoList field.
func (r *mutationResolver) CreateTodoList(ctx context.Context, input CreateTodoListInput) (*entity.TodoList, error) {
	userID, _ := auth.GetUserID(ctx)
	parent := fmt.Sprintf("users/%s", userID)

	return r.todoCreator.CreateTodoList(ctx, inputusecase.CreateTodoListInput{
		Parent:      parent,
		DisplayName: input.DisplayName,
	})
}

// UpdateTodoList is the resolver for the updateTodoList field.
func (r *mutationResolver) UpdateTodoList(ctx context.Context, todoListID string, input UpdateTodoListInput) (*entity.TodoList, error) {
	userID, _ := auth.GetUserID(ctx)
	name := fmt.Sprintf("users/%s/todo-lists/%s", userID, todoListID)

	return r.todoUpdater.UpdateTodoList(ctx, inputusecase.UpdateTodoListInput{
		Name:        name,
		DisplayName: input.DisplayName,
	})
}

// DeleteTodoList is the resolver for the deleteTodoList field.
func (r *mutationResolver) DeleteTodoList(ctx context.Context, todoListID string) (bool, error) {
	userID, _ := auth.GetUserID(ctx)
	name := fmt.Sprintf("users/%s/todo-lists/%s", userID, todoListID)

	if err := r.todoDeleter.DeleteTodoList(ctx, name); err != nil {
		return false, err
	}

	return true, nil
}

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, todoListID string, input CreateTodoInput) (*entity.Todo, error) {
	userID, _ := auth.GetUserID(ctx)
	parent := fmt.Sprintf("users/%s/todo-lists/%s", userID, todoListID)

	in := gateway.CreateTodoInput{
		Title:       input.Title,
		Description: input.Description,
		DueDate:     input.DueDate,
	}

	if input.Priority != nil {
		p := entity.Priority(*input.Priority)
		in.Priority = &p
	}

	if input.AssigneeID != nil {
		in.AssigneeID = input.AssigneeID
	}

	return r.todoCreator.CreateTodo(ctx, parent, inputusecase.CreateTodoInput{
		Title:       input.Title,
		Description: input.Description,
		Priority:    in.Priority,
		DueDate:     input.DueDate,
		AssigneeID:  in.AssigneeID,
	})
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, todoListID string, todoID string, input UpdateTodoInput) (*entity.Todo, error) {
	userID, _ := auth.GetUserID(ctx)
	name := fmt.Sprintf("users/%s/todo-lists/%s/todos/%s", userID, todoListID, todoID)

	in := gateway.UpdateTodoInput{
		Title:       input.Title,
		Description: input.Description,
		DueDate:     input.DueDate,
		AssigneeID:  input.AssigneeID,
	}

	if input.Status != nil {
		s := entity.TodoStatus(*input.Status)
		in.Status = &s
	}

	if input.Priority != nil {
		p := entity.Priority(*input.Priority)
		in.Priority = &p
	}

	return r.todoUpdater.UpdateTodo(ctx, name, inputusecase.UpdateTodoInput{
		Title:       input.Title,
		Description: input.Description,
		Status:      in.Status,
		Priority:    in.Priority,
		DueDate:     input.DueDate,
		AssigneeID:  in.AssigneeID,
	})
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, todoListID string, todoID string) (bool, error) {
	userID, _ := auth.GetUserID(ctx)
	name := fmt.Sprintf("users/%s/todo-lists/%s/todos/%s", userID, todoListID, todoID)

	if err := r.todoDeleter.DeleteTodo(ctx, name); err != nil {
		return false, err
	}

	return true, nil
}

// TodoList is the resolver for the todoList field.
func (r *queryResolver) TodoList(ctx context.Context, todoListID string) (*entity.TodoList, error) {
	userID, _ := auth.GetUserID(ctx)
	name := fmt.Sprintf("users/%s/todo-lists/%s", userID, todoListID)

	return r.todoGetter.GetTodoList(ctx, name)
}

// TodoLists is the resolver for the todoLists field.
func (r *queryResolver) TodoLists(ctx context.Context, input *ListTodoListsInput) (*TodoListPage, error) {
	userID, _ := auth.GetUserID(ctx)
	parent := fmt.Sprintf("users/%s", userID)

	opts := gateway.ListTodoListsOptions{Limit: 20}
	if input != nil {
		if input.PageSize != nil {
			opts.Limit = *input.PageSize
		}
		if input.Offset != nil {
			opts.Offset = *input.Offset
		}
		opts.NameSearch = input.NameSearch
	}

	page, err := r.todoLister.ListTodoLists(ctx, parent, opts)
	if err != nil {
		return nil, err
	}

	return &TodoListPage{TodoLists: page.TodoLists, Total: int(page.Total)}, nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, todoListID string, todoID string) (*entity.Todo, error) {
	userID, _ := auth.GetUserID(ctx)
	name := fmt.Sprintf("users/%s/todo-lists/%s/todos/%s", userID, todoListID, todoID)

	return r.todoGetter.GetTodo(ctx, name)
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, todoListID string, input *ListTodosInput) (*TodoPage, error) {
	userID, _ := auth.GetUserID(ctx)
	parent := fmt.Sprintf("users/%s/todo-lists/%s", userID, todoListID)

	opts := gateway.ListTodosOptions{Limit: 20}
	if input != nil {
		if input.PageSize != nil {
			opts.Limit = *input.PageSize
		}
		if input.Offset != nil {
			opts.Offset = *input.Offset
		}
		opts.TitleSearch = input.TitleSearch
		if input.Status != nil {
			s := entity.TodoStatus(*input.Status)
			opts.Status = &s
		}
		if input.Priority != nil {
			p := entity.Priority(*input.Priority)
			opts.Priority = &p
		}
	}

	page, err := r.todoLister.ListTodos(ctx, parent, opts)
	if err != nil {
		return nil, err
	}

	return &TodoPage{Todos: page.Todos, Total: int(page.Total)}, nil
}

// ID is the resolver for the id field.
func (r *todoResolver) ID(ctx context.Context, obj *entity.Todo) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// TodoListID is the resolver for the todoListId field.
func (r *todoResolver) TodoListID(ctx context.Context, obj *entity.Todo) (string, error) {
	panic(fmt.Errorf("not implemented: TodoListID - todoListId"))
}

// Creator is the resolver for the creator field.
func (r *todoResolver) Creator(ctx context.Context, obj *entity.Todo) (*entity.User, error) {
	if obj.CreatorID == "" {
		return nil, nil
	}

	uID, err := resourcename.ParseUserResourceName(obj.CreatorID)
	if err != nil {
		return nil, err
	}
	userIDStr := strconv.FormatInt(uID, 10)

	loaders := dataloader.For(ctx)
	if loaders != nil && loaders.UserByID != nil {
		user, err := loaders.UserByID.Load(ctx, userIDStr)()
		return user, err
	}

	return r.userGetter.GetByID(ctx, userIDStr)
}

// ID is the resolver for the id field.
func (r *todoListResolver) ID(ctx context.Context, obj *entity.TodoList) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

// TodoList returns TodoListResolver implementation.
func (r *Resolver) TodoList() TodoListResolver { return &todoListResolver{r} }

type todoResolver struct{ *Resolver }
type todoListResolver struct{ *Resolver }
