package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/domain"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, title string, description *string) (*domain.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, name string) (*domain.Todo, error) {
	panic(fmt.Errorf("not implemented: Todo - todo"))
}

// Status is the resolver for the status field.
func (r *todoResolver) Status(ctx context.Context, obj *domain.Todo) (TodoStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// Priority is the resolver for the priority field.
func (r *todoResolver) Priority(ctx context.Context, obj *domain.Todo) (Priority, error) {
	panic(fmt.Errorf("not implemented: Priority - priority"))
}

// Creator is the resolver for the creator field.
func (r *todoResolver) Creator(ctx context.Context, obj *domain.Todo) (*domain.User, error) {
	panic(fmt.Errorf("not implemented: Creator - creator"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
