package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strconv"

	"github.com/nghiapd-andpad/todo-project-intern/pkg/auth"
	"github.com/nghiapd-andpad/todo-project-intern/pkg/resourcename"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/domain/entity"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/handler/dataloader"
	inputusecase "github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/usecase/todo/input"
)

// CreateTodoList is the resolver for the createTodoList field.
func (r *mutationResolver) CreateTodoList(ctx context.Context, input CreateTodoListInput) (*entity.TodoList, error) {
	if input.DisplayName == "" {
		return nil, entity.NewInvalidParameter("display_name is required")
	}

	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("user ID not found in context")
	}

	parent := fmt.Sprintf("users/%s", userID)

	return r.todoCreator.CreateTodoList(ctx, inputusecase.CreateTodoListInput{
		Parent:      parent,
		DisplayName: input.DisplayName,
	})
}

// UpdateTodoList is the resolver for the updateTodoList field.
func (r *mutationResolver) UpdateTodoList(ctx context.Context, input UpdateTodoListInput) (*entity.TodoList, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("user ID not found in context")
	}

	name := fmt.Sprintf("users/%s/todo-lists/%s", userID, input.TodoListID)

	return r.todoUpdater.UpdateTodoList(ctx, inputusecase.UpdateTodoListInput{
		Name:        name,
		DisplayName: input.DisplayName,
	})
}

// DeleteTodoList is the resolver for the deleteTodoList field.
func (r *mutationResolver) DeleteTodoList(ctx context.Context, input DeleteTodoListInput) (bool, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return false, fmt.Errorf("user ID not found in context")
	}

	name := fmt.Sprintf("users/%s/todo-lists/%s", userID, input.TodoListID)

	if err := r.todoDeleter.DeleteTodoList(ctx, name); err != nil {
		return false, err
	}

	return true, nil
}

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input CreateTodoInput) (*entity.Todo, error) {
	if input.Title == "" {
		return nil, entity.NewInvalidParameter("title is required")
	}

	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("user ID not found in context")
	}

	in := inputusecase.CreateTodoInput{
		Parent:      fmt.Sprintf("users/%s/todo-lists/%s", userID, input.TodoListID),
		Title:       input.Title,
		Description: input.Description,
		DueDate:     input.DueDate,
	}
	if input.Priority != nil {
		p := entity.Priority(*input.Priority)
		in.Priority = &p
	}
	if input.AssigneeID != nil {
		in.AssigneeID = input.AssigneeID
	}

	return r.todoCreator.CreateTodo(ctx, in)
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, input UpdateTodoInput) (*entity.Todo, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("user ID not found in context")
	}

	in := inputusecase.UpdateTodoInput{
		Name:        fmt.Sprintf("users/%s/todo-lists/%s/todos/%s", userID, input.TodoListID, input.TodoID),
		Title:       input.Title,
		Description: input.Description,
		DueDate:     input.DueDate,
		AssigneeID:  input.AssigneeID,
	}
	if input.Status != nil {
		s := entity.TodoStatus(*input.Status)
		in.Status = &s
	}
	if input.Priority != nil {
		p := entity.Priority(*input.Priority)
		in.Priority = &p
	}

	return r.todoUpdater.UpdateTodo(ctx, in)
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, input DeleteTodoInput) (bool, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return false, fmt.Errorf("user ID not found in context")
	}

	name := fmt.Sprintf("users/%s/todo-lists/%s/todos/%s", userID, input.TodoListID, input.TodoID)

	if err := r.todoDeleter.DeleteTodo(ctx, name); err != nil {
		return false, err
	}

	return true, nil
}

// TodoList is the resolver for the todoList field.
func (r *queryResolver) TodoList(ctx context.Context, input GetTodoListInput) (*entity.TodoList, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("user ID not found in context")
	}

	name := fmt.Sprintf("users/%s/todo-lists/%s", userID, input.TodoListID)

	return r.todoGetter.GetTodoList(ctx, name)
}

// TodoLists is the resolver for the todoLists field.
func (r *queryResolver) TodoLists(ctx context.Context, input ListTodoListsInput) (*TodoListPage, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("user ID not found in context")
	}

	parent := fmt.Sprintf("users/%s", userID)

	opts := inputusecase.ListTodoListsOptions{Limit: 20}
	if input.PageSize != nil {
		opts.Limit = *input.PageSize
	}
	if input.Offset != nil {
		opts.Offset = *input.Offset
	}
	opts.NameSearch = input.NameSearch

	page, err := r.todoLister.ListTodoLists(ctx, parent, opts)
	if err != nil {
		return nil, err
	}

	return &TodoListPage{TodoLists: page.TodoLists, Total: int(page.Total)}, nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, input GetTodoInput) (*entity.Todo, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("user ID not found in context")
	}

	name := fmt.Sprintf("users/%s/todo-lists/%s/todos/%s", userID, input.TodoListID, input.TodoID)

	return r.todoGetter.GetTodo(ctx, name)
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, input ListTodosInput) (*TodoPage, error) {
	userID, ok := auth.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("user ID not found in context")
	}

	parent := fmt.Sprintf("users/%s/todo-lists/%s", userID, input.TodoListID)

	opts := inputusecase.ListTodosOptions{Limit: 20}
	if input.PageSize != nil {
		opts.Limit = *input.PageSize
	}
	if input.Offset != nil {
		opts.Offset = *input.Offset
	}
	opts.TitleSearch = input.TitleSearch
	if input.Status != nil {
		s := entity.TodoStatus(*input.Status)
		opts.Status = &s
	}
	if input.Priority != nil {
		p := entity.Priority(*input.Priority)
		opts.Priority = &p
	}

	page, err := r.todoLister.ListTodos(ctx, parent, opts)
	if err != nil {
		return nil, err
	}

	return &TodoPage{Todos: page.Todos, Total: int(page.Total)}, nil
}

// Creator is the resolver for the creator field.
func (r *todoResolver) Creator(ctx context.Context, obj *entity.Todo) (*entity.User, error) {
	if obj.CreatorID == "" {
		return nil, nil
	}

	uID, err := resourcename.ParseUserResourceName(obj.CreatorID)
	if err != nil {
		return nil, err
	}
	userIDStr := strconv.FormatInt(uID, 10)

	loaders := dataloader.For(ctx)
	if loaders != nil && loaders.UserByID != nil {
		user, err := loaders.UserByID.Load(ctx, userIDStr)()
		return user, err
	}

	return r.userGetter.GetByID(ctx, userIDStr)
}

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type todoResolver struct{ *Resolver }
