package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/domain/entity"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, password string, email string) (*entity.User, error) {
	return r.authUsecase.Register(ctx, username, password, email)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*AuthPayload, error) {
	token, user, err := r.loginUsecase.Login(ctx, username, password)
	if err != nil {
		return nil, err
	}
	return &AuthPayload{Token: token, User: user}, nil
}

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, id string) (*entity.User, error) {
	return r.userGetter.GetByID(ctx, id)
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (*entity.User, error) {
	return r.userGetter.GetByUsername(ctx, username)
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*entity.User, error) {
	return r.userGetter.GetByEmail(ctx, email)
}
