package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/domain"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/usecase/auth/input"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, password string, email string) (*domain.User, error) {
	// Convert input data to RegisterInput struct
	in := &input.RegisterInput{
		Username: username,
		Email:    email,
		Password: password,
	}

	// Execute the UseCase
	user, err := r.AuthUseCase.Register(ctx, in)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*AuthPayload, error) {
	// Convert input data to LoginInput struct
	in := &input.LoginInput{
		Username: username,
		Password: password,
	}

	// Execute the UseCase
	out, err := r.AuthUseCase.Login(ctx, in)
	if err != nil {
		return nil, err
	}

	// Convert output data
	return &AuthPayload{
		Token: out.AccessToken,
		User:  out.User,
	}, nil
}
