package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/domain/entity"
	authinput "github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/usecase/auth/input"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input RegisterInput) (*entity.User, error) {
	if input.Username == "" || input.Password == "" || input.Email == "" {
		return nil, entity.NewInvalidParameter("username, password and email are required")
	}

	return r.authRegisterer.Register(ctx, authinput.RegisterInput{
		Username: input.Username,
		Password: input.Password,
		Email:    input.Email,
	})
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*AuthPayload, error) {
	if input.Username == "" || input.Password == "" {
		return nil, entity.NewInvalidParameter("username and password are required")
	}

	loginOutput, err := r.authLoginer.Login(ctx, authinput.LoginInput{
		Username: input.Username,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}

	return &AuthPayload{Token: loginOutput.AccessToken, User: loginOutput.User}, nil
}

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, input GetUserInput) (*entity.User, error) {
	return r.userGetter.GetByID(ctx, input.ID)
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, input GetUserByUsernameInput) (*entity.User, error) {
	return r.userGetter.GetByUsername(ctx, input.Username)
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, input GetUserByEmailInput) (*entity.User, error) {
	return r.userGetter.GetByEmail(ctx, input.Email)
}
