// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/config"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/handler/grpc/user"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/infra/persistence"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/infra/security"
	user2 "github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/usecase/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeUserHandler(db *gorm.DB, cfg *config.Config) (*user.UserHandler, error) {
	userCommandsGateway := persistence.NewUserRepository(db)
	userCreator := user2.NewUserCreator(userCommandsGateway)
	userQueriesGateway := persistence.NewUserQueryRepository(db)
	tokenGenerator := security.NewJWTManager(cfg)
	userAuthenticator := user2.NewUserAuthenticator(userQueriesGateway, tokenGenerator)
	userHandler := user.NewUserHandler(userCreator, userAuthenticator)
	return userHandler, nil
}
