// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/config"
	user2 "github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/handler/grpc/user"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/infra/persistence"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/infra/security"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/usecase/user"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*grpc.Server, func(), error) {
	db, cleanup, err := persistence.NewDatabase(cfg)
	if err != nil {
		return nil, nil, err
	}
	userCommandsGateway := persistence.NewUserCommandsGateway(db)
	userQueriesGateway := persistence.NewUserQueryGateway(db)
	userCreator := user.NewUserCreator(userCommandsGateway, userQueriesGateway)
	tokenManager := security.NewJWTManager(cfg)
	userAuthenticator := user.NewUserAuthenticator(userQueriesGateway, tokenManager)
	userGetter := user.NewUserGetter(userQueriesGateway)
	userHandler := user2.NewUserHandler(userCreator, userAuthenticator, userGetter)
	server := user2.NewGRPCServer(cfg, userHandler)
	return server, func() {
		cleanup()
	}, nil
}
