// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/config"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/handler"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/infra/persistence"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/infra/security"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-user/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*grpc.Server, func(), error) {
	db, cleanup, err := persistence.NewDatabase(cfg)
	if err != nil {
		return nil, nil, err
	}
	userCommandsGateway := persistence.NewUserCommandsGateway(db)
	userQueriesGateway := persistence.NewUserQueryGateway(db)
	userCreator := service.NewUserCreator(userCommandsGateway, userQueriesGateway)
	jwtManager := security.NewJWTManager(cfg)
	userAuthenticator := service.NewUserAuthenticator(userQueriesGateway, jwtManager, cfg)
	userGetter := service.NewUserGetter(userQueriesGateway)
	userHandler := handler.NewUserHandler(userCreator, userAuthenticator, userGetter)
	server, err := handler.NewGRPCServer(cfg, userHandler)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup()
	}, nil
}
