// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/config"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/handler/grpc/todo"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/infra/persistence"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/usecase/todos"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*grpc.Server, func(), error) {
	db, cleanup, err := persistence.NewDatabase(cfg)
	if err != nil {
		return nil, nil, err
	}
	todoCommandsGateway := persistence.NewTodoCommandsGateway(db)
	todoCreator := todos.NewTodoCreator(todoCommandsGateway)
	todoQueriesGateway := persistence.NewTodoQueriesGateway(db)
	todoGetter := todos.NewTodoGetter(todoQueriesGateway)
	todoLister := todos.NewTodoLister(todoQueriesGateway)
	todoUpdater := todos.NewTodoUpdater(todoCommandsGateway, todoQueriesGateway)
	todoDeleter := todos.NewTodoDeleter(todoCommandsGateway, todoQueriesGateway)
	todoListCommandsGateway := persistence.NewTodoListCommandsGateway(db)
	todoListCreator := todos.NewTodoListCreator(todoListCommandsGateway)
	todoListQueriesGateway := persistence.NewTodoListQueriesGateway(db)
	todoListGetter := todos.NewTodoListGetter(todoListQueriesGateway)
	todoListLister := todos.NewTodoListLister(todoListQueriesGateway)
	todoListUpdater := todos.NewTodoListUpdater(todoListCommandsGateway, todoListQueriesGateway)
	todoListDeleter := todos.NewTodoListDeleter(todoListCommandsGateway)
	todoHandler := todo.NewTodoHandler(todoCreator, todoGetter, todoLister, todoUpdater, todoDeleter, todoListCreator, todoListGetter, todoListLister, todoListUpdater, todoListDeleter)
	server, cleanup2, err := todo.ProvideGRPCServer(cfg, todoHandler)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}
