// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/config"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/handler"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/infra/persistence"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*grpc.Server, func(), error) {
	db, cleanup, err := persistence.NewDatabase(cfg)
	if err != nil {
		return nil, nil, err
	}
	todoListQueriesGateway := persistence.NewTodoListQueriesGateway(db)
	todoCommandsGateway := persistence.NewTodoCommandsGateway(db)
	todoCreator := service.NewTodoCreator(todoListQueriesGateway, todoCommandsGateway, cfg)
	todoQueriesGateway := persistence.NewTodoQueriesGateway(db)
	todoGetter := service.NewTodoGetter(todoListQueriesGateway, todoQueriesGateway)
	todoLister := service.NewTodoLister(todoListQueriesGateway, todoQueriesGateway)
	todoUpdater := service.NewTodoUpdater(todoListQueriesGateway, todoQueriesGateway, todoCommandsGateway)
	todoDeleter := service.NewTodoDeleter(todoListQueriesGateway, todoQueriesGateway, todoCommandsGateway)
	todoListCommandsGateway := persistence.NewTodoListCommandsGateway(db)
	todoListCreator := service.NewTodoListCreator(todoListCommandsGateway)
	todoListGetter := service.NewTodoListGetter(todoListQueriesGateway)
	todoListLister := service.NewTodoListLister(todoListQueriesGateway)
	todoListUpdater := service.NewTodoListUpdater(todoListCommandsGateway, todoListQueriesGateway)
	transactor := persistence.NewTransactor(db)
	todoListDeleter := service.NewTodoListDeleter(transactor, todoListQueriesGateway, todoListCommandsGateway, todoCommandsGateway)
	todoHandler := handler.NewTodoHandler(todoCreator, todoGetter, todoLister, todoUpdater, todoDeleter, todoListCreator, todoListGetter, todoListLister, todoListUpdater, todoListDeleter)
	server, err := handler.NewGRPCServer(cfg, todoHandler)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup()
	}, nil
}
