// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/config"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/handler"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/infra/cronjob"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/infra/persistence"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/infra/redis"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/service"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/utils/logger"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/worker"
	"github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/worker/job"
	"go.uber.org/zap"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config) (*ServerApp, func(), error) {
	db, cleanup, err := persistence.NewDatabase(cfg)
	if err != nil {
		return nil, nil, err
	}
	transactor := persistence.NewTransactor(db)
	idempotencyGateway := persistence.NewIdempotencyGateway(db)
	todoQueriesGateway := persistence.NewTodoQueriesGateway(db)
	todoCommandsGateway := persistence.NewTodoCommandsGateway(db)
	todoListQueriesGateway := persistence.NewTodoListQueriesGateway(db)
	todoCreator := service.NewTodoCreator(cfg, transactor, idempotencyGateway, todoQueriesGateway, todoCommandsGateway, todoListQueriesGateway)
	todoGetter := service.NewTodoGetter(todoListQueriesGateway, todoQueriesGateway)
	todoLister := service.NewTodoLister(todoListQueriesGateway, todoQueriesGateway)
	todoUpdater := service.NewTodoUpdater(transactor, todoListQueriesGateway, todoQueriesGateway, todoCommandsGateway)
	todoDeleter := service.NewTodoDeleter(todoListQueriesGateway, todoQueriesGateway, todoCommandsGateway)
	todoListCommandsGateway := persistence.NewTodoListCommandsGateway(db)
	todoListCreator := service.NewTodoListCreator(transactor, idempotencyGateway, todoListQueriesGateway, todoListCommandsGateway)
	todoListGetter := service.NewTodoListGetter(todoListQueriesGateway)
	todoListLister := service.NewTodoListLister(todoListQueriesGateway)
	todoListUpdater := service.NewTodoListUpdater(transactor, todoListCommandsGateway, todoListQueriesGateway)
	todoListDeleter := service.NewTodoListDeleter(transactor, todoListQueriesGateway, todoListCommandsGateway, todoCommandsGateway)
	todoHandler := handler.NewTodoHandler(todoCreator, todoGetter, todoLister, todoUpdater, todoDeleter, todoListCreator, todoListGetter, todoListLister, todoListUpdater, todoListDeleter)
	zapLogger, cleanup2, err := logger.New(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	server, err := handler.NewGRPCServer(cfg, todoHandler, zapLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serverApp := NewServerApp(server, zapLogger)
	return serverApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

func InitializeWorker(cfg *config.Config) (*WorkerApp, func(), error) {
	zapLogger, cleanup, err := logger.New(cfg)
	if err != nil {
		return nil, nil, err
	}
	scheduler, cleanup2, err := cronjob.NewScheduler(zapLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	db, cleanup3, err := persistence.NewDatabase(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	todoQueriesGateway := persistence.NewTodoQueriesGateway(db)
	todoCommandsGateway := persistence.NewTodoCommandsGateway(db)
	todoOverdueMarker := service.NewTodoOverdueMarker(todoQueriesGateway, todoCommandsGateway)
	client, cleanup4, err := redis.NewClient(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	distributedLocker := redis.NewDistributedLocker(client)
	todoOverdueMarkerJob := job.NewTodoOverdueMarkerJob(todoOverdueMarker, distributedLocker, cfg, zapLogger)
	transactor := persistence.NewTransactor(db)
	todoListQueriesGateway := persistence.NewTodoListQueriesGateway(db)
	todoListCommandsGateway := persistence.NewTodoListCommandsGateway(db)
	todoSoftDeletedCleaner := service.NewTodoSoftDeletedCleaner(transactor, todoQueriesGateway, todoCommandsGateway, todoListQueriesGateway, todoListCommandsGateway)
	todoSoftDeletedCleanupJob := job.NewTodoSoftDeletedCleanupJob(todoSoftDeletedCleaner, distributedLocker, cfg, zapLogger)
	workerWorker := worker.NewWorker(cfg, scheduler, todoOverdueMarkerJob, todoSoftDeletedCleanupJob, zapLogger)
	workerApp := NewWorkerApp(workerWorker, zapLogger)
	return workerApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type ServerApp struct {
	GRPCServer *grpc.Server
	Logger     *zap.Logger
}

type WorkerApp struct {
	Worker *worker.Worker
	Logger *zap.Logger
}

func NewWorkerApp(worker2 *worker.Worker, zapLogger *zap.Logger) *WorkerApp {
	return &WorkerApp{
		Worker: worker2,
		Logger: zapLogger,
	}
}

func NewServerApp(grpcServer *grpc.Server, zapLogger *zap.Logger) *ServerApp {
	return &ServerApp{
		GRPCServer: grpcServer,
		Logger:     zapLogger,
	}
}
