// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nghiapd-andpad/todo-project-intern/services/todo-service/internal/handler/grpc/todo"
	"github.com/nghiapd-andpad/todo-project-intern/services/todo-service/internal/infra/persistence"
	"github.com/nghiapd-andpad/todo-project-intern/services/todo-service/internal/usecase/todos"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeTodoHandler(db *gorm.DB) *todo.TodoHandler {
	todoCommandsGateway := persistence.NewTodoCommandsGateway(db)
	todoCreator := todos.NewTodoCreator(todoCommandsGateway)
	todoQueriesGateway := persistence.NewTodoQueriesGateway(db)
	todoGetter := todos.NewTodoGetter(todoQueriesGateway)
	todoLister := todos.NewTodoListReader(todoQueriesGateway)
	todoUpdater := todos.NewTodoUpdater(todoCommandsGateway, todoQueriesGateway)
	todoDeleter := todos.NewTodoDeleter(todoCommandsGateway)
	todoHandler := todo.NewTodoHandler(todoCreator, todoGetter, todoLister, todoUpdater, todoDeleter)
	return todoHandler
}
