// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nghiapd-andpad/todo-project-intern/gateways/todo-bff/internal/handler/graph"
	"github.com/nghiapd-andpad/todo-project-intern/gateways/todo-bff/internal/infra/grpc_client"
	"github.com/nghiapd-andpad/todo-project-intern/gateways/todo-bff/internal/usecase/auth"
	"github.com/nghiapd-andpad/todo-project-intern/proto/user/v1"
)

// Injectors from wire.go:

func InitializeResolver(userSvc userv1.UserServiceClient) *graph.Resolver {
	authGateway := grpc_client.NewAuthServiceClient(userSvc)
	authUseCase := auth.NewAuthUseCase(authGateway)
	resolver := graph.NewResolver(authUseCase)
	return resolver
}
