// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/config"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/handler/graph"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/infra/grpcclient"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/infra/jwt"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/service/auth"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/service/todo"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/service/user"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, func(), error) {
	todoGateway, cleanup, err := grpcclient.NewTodoGateway(cfg)
	if err != nil {
		return nil, nil, err
	}
	todoCreator := todo.NewTodoCreator(todoGateway)
	todoGetter := todo.NewTodoGetter(todoGateway)
	todoLister := todo.NewTodoLister(todoGateway)
	todoUpdater := todo.NewTodoUpdater(todoGateway)
	todoDeleter := todo.NewTodoDeleter(todoGateway)
	authGateway, cleanup2, err := grpcclient.NewAuthGateway(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	registerer := auth.NewRegisterer(authGateway)
	loginer := auth.NewLoginer(authGateway)
	userGateway, cleanup3, err := grpcclient.NewUserGateway(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userGetter := user.NewUserGetter(userGateway)
	resolver := graph.NewResolver(todoCreator, todoGetter, todoLister, todoUpdater, todoDeleter, registerer, loginer, userGetter)
	jwtManager := jwt.NewJwtManager(cfg)
	app := &App{
		Resolver:   resolver,
		JwtManager: jwtManager,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type App struct {
	Resolver   *graph.Resolver
	JwtManager *jwt.JwtManager
}
