// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/handler/graph"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/infra/grpc_client"
	"github.com/nghiapd-andpad/todo-project-intern/services/bff-web/internal/usecase/auth"
)

// Injectors from wire.go:

func InitializeResolver() (*graph.Resolver, func(), error) {
	clientConn, cleanup, err := grpc_client.NewUserGRPCConn()
	if err != nil {
		return nil, nil, err
	}
	userServiceClient := grpc_client.NewUserServiceClient(clientConn)
	authGateway := grpc_client.NewAuthServiceClient(userServiceClient)
	authUseCase := auth.NewAuthUseCase(authGateway)
	resolver := graph.NewResolver(authUseCase)
	return resolver, func() {
		cleanup()
	}, nil
}
