// Code generated by MockGen. DO NOT EDIT.
// Source: audit_log_commands.go
//
// Generated by this command:
//
//	mockgen -destination=mock/audit_log_commands_mock.go -source=audit_log_commands.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	input "github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/domain/gateway/input"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditLogCommandsGateway is a mock of AuditLogCommandsGateway interface.
type MockAuditLogCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockAuditLogCommandsGatewayMockRecorder is the mock recorder for MockAuditLogCommandsGateway.
type MockAuditLogCommandsGatewayMockRecorder struct {
	mock *MockAuditLogCommandsGateway
}

// NewMockAuditLogCommandsGateway creates a new mock instance.
func NewMockAuditLogCommandsGateway(ctrl *gomock.Controller) *MockAuditLogCommandsGateway {
	mock := &MockAuditLogCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockAuditLogCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogCommandsGateway) EXPECT() *MockAuditLogCommandsGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuditLogCommandsGateway) Create(ctx context.Context, in *input.CreateAuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuditLogCommandsGatewayMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditLogCommandsGateway)(nil).Create), ctx, in)
}
