// Code generated by MockGen. DO NOT EDIT.
// Source: outbox_event_commands.go
//
// Generated by this command:
//
//	mockgen -destination=mock/outbox_event_commands_mock.go -source=outbox_event_commands.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	input "github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/domain/gateway/input"
	model "github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/infra/persistence/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxEventCommandsGateway is a mock of OutboxEventCommandsGateway interface.
type MockOutboxEventCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxEventCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockOutboxEventCommandsGatewayMockRecorder is the mock recorder for MockOutboxEventCommandsGateway.
type MockOutboxEventCommandsGatewayMockRecorder struct {
	mock *MockOutboxEventCommandsGateway
}

// NewMockOutboxEventCommandsGateway creates a new mock instance.
func NewMockOutboxEventCommandsGateway(ctrl *gomock.Controller) *MockOutboxEventCommandsGateway {
	mock := &MockOutboxEventCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockOutboxEventCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxEventCommandsGateway) EXPECT() *MockOutboxEventCommandsGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOutboxEventCommandsGateway) Create(ctx context.Context, in *input.CreateOutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboxEventCommandsGatewayMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxEventCommandsGateway)(nil).Create), ctx, in)
}

// FindPending mocks base method.
func (m *MockOutboxEventCommandsGateway) FindPending(ctx context.Context, in *input.ListPendingOutboxEvents) ([]*model.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPending", ctx, in)
	ret0, _ := ret[0].([]*model.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPending indicates an expected call of FindPending.
func (mr *MockOutboxEventCommandsGatewayMockRecorder) FindPending(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPending", reflect.TypeOf((*MockOutboxEventCommandsGateway)(nil).FindPending), ctx, in)
}

// MarkFailed mocks base method.
func (m *MockOutboxEventCommandsGateway) MarkFailed(ctx context.Context, id int64, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockOutboxEventCommandsGatewayMockRecorder) MarkFailed(ctx, id, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockOutboxEventCommandsGateway)(nil).MarkFailed), ctx, id, errMsg)
}

// MarkPublished mocks base method.
func (m *MockOutboxEventCommandsGateway) MarkPublished(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockOutboxEventCommandsGatewayMockRecorder) MarkPublished(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockOutboxEventCommandsGateway)(nil).MarkPublished), ctx, id)
}
