// Code generated by MockGen. DO NOT EDIT.
// Source: todo_commands.go
//
// Generated by this command:
//
//	mockgen -destination=mock/todo_commands_mock.go -source=todo_commands.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTodoCommandsGateway is a mock of TodoCommandsGateway interface.
type MockTodoCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTodoCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockTodoCommandsGatewayMockRecorder is the mock recorder for MockTodoCommandsGateway.
type MockTodoCommandsGatewayMockRecorder struct {
	mock *MockTodoCommandsGateway
}

// NewMockTodoCommandsGateway creates a new mock instance.
func NewMockTodoCommandsGateway(ctrl *gomock.Controller) *MockTodoCommandsGateway {
	mock := &MockTodoCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockTodoCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoCommandsGateway) EXPECT() *MockTodoCommandsGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTodoCommandsGateway) Create(ctx context.Context, todo *entity.Todo) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, todo)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTodoCommandsGatewayMockRecorder) Create(ctx, todo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTodoCommandsGateway)(nil).Create), ctx, todo)
}

// Delete mocks base method.
func (m *MockTodoCommandsGateway) Delete(ctx context.Context, todoID entity.TodoID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, todoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTodoCommandsGatewayMockRecorder) Delete(ctx, todoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTodoCommandsGateway)(nil).Delete), ctx, todoID)
}

// DeleteByTodoListID mocks base method.
func (m *MockTodoCommandsGateway) DeleteByTodoListID(ctx context.Context, todoListID entity.TodoListID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTodoListID", ctx, todoListID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTodoListID indicates an expected call of DeleteByTodoListID.
func (mr *MockTodoCommandsGatewayMockRecorder) DeleteByTodoListID(ctx, todoListID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTodoListID", reflect.TypeOf((*MockTodoCommandsGateway)(nil).DeleteByTodoListID), ctx, todoListID)
}

// Update mocks base method.
func (m *MockTodoCommandsGateway) Update(ctx context.Context, todo *entity.Todo) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, todo)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTodoCommandsGatewayMockRecorder) Update(ctx, todo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTodoCommandsGateway)(nil).Update), ctx, todo)
}
