// Code generated by MockGen. DO NOT EDIT.
// Source: todo_list_queries.go
//
// Generated by this command:
//
//	mockgen -destination=mock/todo_list_queries_mock.go -source=todo_list_queries.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/domain/entity"
	input "github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/domain/gateway/input"
	gomock "go.uber.org/mock/gomock"
)

// MockTodoListQueriesGateway is a mock of TodoListQueriesGateway interface.
type MockTodoListQueriesGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTodoListQueriesGatewayMockRecorder
	isgomock struct{}
}

// MockTodoListQueriesGatewayMockRecorder is the mock recorder for MockTodoListQueriesGateway.
type MockTodoListQueriesGatewayMockRecorder struct {
	mock *MockTodoListQueriesGateway
}

// NewMockTodoListQueriesGateway creates a new mock instance.
func NewMockTodoListQueriesGateway(ctrl *gomock.Controller) *MockTodoListQueriesGateway {
	mock := &MockTodoListQueriesGateway{ctrl: ctrl}
	mock.recorder = &MockTodoListQueriesGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoListQueriesGateway) EXPECT() *MockTodoListQueriesGatewayMockRecorder {
	return m.recorder
}

// FindSoftDeletedTodoListIDs mocks base method.
func (m *MockTodoListQueriesGateway) FindSoftDeletedTodoListIDs(ctx context.Context, cutoff time.Time, limit int) ([]entity.TodoListID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSoftDeletedTodoListIDs", ctx, cutoff, limit)
	ret0, _ := ret[0].([]entity.TodoListID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSoftDeletedTodoListIDs indicates an expected call of FindSoftDeletedTodoListIDs.
func (mr *MockTodoListQueriesGatewayMockRecorder) FindSoftDeletedTodoListIDs(ctx, cutoff, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSoftDeletedTodoListIDs", reflect.TypeOf((*MockTodoListQueriesGateway)(nil).FindSoftDeletedTodoListIDs), ctx, cutoff, limit)
}

// Get mocks base method.
func (m *MockTodoListQueriesGateway) Get(ctx context.Context, todoListID entity.TodoListID) (*entity.TodoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, todoListID)
	ret0, _ := ret[0].(*entity.TodoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTodoListQueriesGatewayMockRecorder) Get(ctx, todoListID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTodoListQueriesGateway)(nil).Get), ctx, todoListID)
}

// GetForUpdate mocks base method.
func (m *MockTodoListQueriesGateway) GetForUpdate(ctx context.Context, todoListID entity.TodoListID) (*entity.TodoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForUpdate", ctx, todoListID)
	ret0, _ := ret[0].(*entity.TodoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForUpdate indicates an expected call of GetForUpdate.
func (mr *MockTodoListQueriesGatewayMockRecorder) GetForUpdate(ctx, todoListID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForUpdate", reflect.TypeOf((*MockTodoListQueriesGateway)(nil).GetForUpdate), ctx, todoListID)
}

// List mocks base method.
func (m *MockTodoListQueriesGateway) List(ctx context.Context, opts *input.ListTodoListsOptions) ([]*entity.TodoList, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*entity.TodoList)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTodoListQueriesGatewayMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTodoListQueriesGateway)(nil).List), ctx, opts)
}
