// Code generated by MockGen. DO NOT EDIT.
// Source: todo_list_commands.go
//
// Generated by this command:
//
//	mockgen -destination=mock/todo_list_commands_mock.go -source=todo_list_commands.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTodoListCommandsGateway is a mock of TodoListCommandsGateway interface.
type MockTodoListCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTodoListCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockTodoListCommandsGatewayMockRecorder is the mock recorder for MockTodoListCommandsGateway.
type MockTodoListCommandsGatewayMockRecorder struct {
	mock *MockTodoListCommandsGateway
}

// NewMockTodoListCommandsGateway creates a new mock instance.
func NewMockTodoListCommandsGateway(ctrl *gomock.Controller) *MockTodoListCommandsGateway {
	mock := &MockTodoListCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockTodoListCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoListCommandsGateway) EXPECT() *MockTodoListCommandsGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTodoListCommandsGateway) Create(ctx context.Context, todoList *entity.TodoList) (*entity.TodoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, todoList)
	ret0, _ := ret[0].(*entity.TodoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTodoListCommandsGatewayMockRecorder) Create(ctx, todoList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTodoListCommandsGateway)(nil).Create), ctx, todoList)
}

// Delete mocks base method.
func (m *MockTodoListCommandsGateway) Delete(ctx context.Context, todoListID entity.TodoListID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, todoListID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTodoListCommandsGatewayMockRecorder) Delete(ctx, todoListID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTodoListCommandsGateway)(nil).Delete), ctx, todoListID)
}

// Update mocks base method.
func (m *MockTodoListCommandsGateway) Update(ctx context.Context, todoList *entity.TodoList) (*entity.TodoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, todoList)
	ret0, _ := ret[0].(*entity.TodoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTodoListCommandsGatewayMockRecorder) Update(ctx, todoList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTodoListCommandsGateway)(nil).Update), ctx, todoList)
}
