// Code generated by MockGen. DO NOT EDIT.
// Source: todo_queries.go
//
// Generated by this command:
//
//	mockgen -destination=mock/todo_queries_mock.go -source=todo_queries.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/domain/entity"
	input "github.com/nghiapd-andpad/todo-project-intern/services/core-todo/internal/domain/gateway/input"
	gomock "go.uber.org/mock/gomock"
)

// MockTodoQueriesGateway is a mock of TodoQueriesGateway interface.
type MockTodoQueriesGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTodoQueriesGatewayMockRecorder
	isgomock struct{}
}

// MockTodoQueriesGatewayMockRecorder is the mock recorder for MockTodoQueriesGateway.
type MockTodoQueriesGatewayMockRecorder struct {
	mock *MockTodoQueriesGateway
}

// NewMockTodoQueriesGateway creates a new mock instance.
func NewMockTodoQueriesGateway(ctrl *gomock.Controller) *MockTodoQueriesGateway {
	mock := &MockTodoQueriesGateway{ctrl: ctrl}
	mock.recorder = &MockTodoQueriesGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoQueriesGateway) EXPECT() *MockTodoQueriesGatewayMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTodoQueriesGateway) Get(ctx context.Context, todoID entity.TodoID, todoListID entity.TodoListID) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, todoID, todoListID)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTodoQueriesGatewayMockRecorder) Get(ctx, todoID, todoListID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTodoQueriesGateway)(nil).Get), ctx, todoID, todoListID)
}

// List mocks base method.
func (m *MockTodoQueriesGateway) List(ctx context.Context, opts *input.ListTodosOptions) ([]*entity.Todo, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*entity.Todo)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTodoQueriesGatewayMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTodoQueriesGateway)(nil).List), ctx, opts)
}
